version: "3"
services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        hostname: localhost
        restart: unless-stopped
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                gitlab_rails['gitlab_shell_ssh_port'] = 22
        ports: 
            - "9300:80"
            - "9322:22"
        volumes:
            - ./config/gitlab:/etc/gitlab
            - ./data/gitlab:/var/opt/gitlab
            - ./logs:/var/log/gitlab
        networks:
            - gitlab

    gitlab-runner:
        image: gitlab/gitlab-runner:alpine
        restart: unless-stopped
        depends_on:
            - gitlab
        privileged: true
        volumes:
            - ./config/gitlab-runner:/etc/gitlab-runner
            - /var/run/docker.sock:/var/run/docker.sock
            - /bin/docker:/bin/docker
        networks:
            - gitlab
    gitlab-ci-pipelines-exporter:
        image: mvisonneau/gitlab-ci-pipelines-exporter:latest
        environment:
            GCPE_CONFIG: /etc/config.yml
            GCPE_LOG_LEVEL: debug
        depends_on: 
            - gitlab
        volumes:
          - ./config/gitlab-ci-pipelines-exporter/config.yml:/etc/config.yml
        ports:
            - "9380:8080"
        networks:
            - gitlab
    prometheus:
        image: prom/prometheus:v2.22.2
        ports:
            - "9390:9090"
        links:
            - gitlab-ci-pipelines-exporter
        volumes:
            - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml
        networks: 
            - gitlab

    grafana:
        image: grafana/grafana:7.3.3
        ports:
            - "9000:3000"
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_INSTALL_PLUGINS: grafana-polystat-panel,yesoreyeram-boomtable-panel
        links:
            - prometheus
        volumes:
            - ./config/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
            - ./config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/default.yml
            - ./config/grafana/dashboards:/var/lib/grafana/dashboards
networks:
    gitlab:
        driver: bridge