{
 "title": "GitLab CI jobs",
 "description": "This dashboard leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses. More information here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "GITLAB_HOST", "query": "gitlab.com" },
   {
    "name": "OWNER",
    "label": "owner",
    "query": "label_values(gitlab_ci_pipeline_id, project)"
   },
   {
    "name": "PROJECT",
    "label": "project",
    "query": "label_values(gitlab_ci_pipeline_id{project=~\"$OWNER.*\"}, project)"
   },
   {
    "name": "REF",
    "label": "ref",
    "query": "label_values(gitlab_ci_pipeline_id{project=~\"$PROJECT\"}, ref)"
   },
   {
    "name": "JOB",
    "label": "job",
    "query": "label_values(gitlab_ci_pipeline_job_id{project=~\"$PROJECT\", ref=~\"$REF\"}, job_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://www.cloudfoundry.org/wp-content/uploads/2017/10/icon_gitlab_cf@2x.png\" width=80px/></p>"
   }
  },
  {
   "title": "JOBS #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_job_run_count{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"})"
    }
   ]
  },
  {
   "title": "FAILED JOBS #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_job_status{status=\"failed\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "RUNS # (in the last hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_ci_pipeline_job_run_count{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}[1h]))"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "(gitlab_ci_pipeline_job_status{status=\"success\", project=~\"$OWNER.*\", ref=~\"$REF\", job_name=~\"$JOB\"} * 1 > 0) or (gitlab_ci_pipeline_job_status{status=\"running\", project=~\"$OWNER.*\", ref=~\"$REF\", job_name=~\"$JOB\"} * 2 > 0) or (gitlab_ci_pipeline_job_status{status=~\"failed|canceled\", project=~\"$OWNER.*\", ref=~\"$REF\", job_name=~\"$JOB\"} * 3 > 0) or (gitlab_ci_pipeline_job_status{status!~\"success|running|failed|canceled\", project=~\"$OWNER.*\", ref=~\"$REF\", job_name=~\"$JOB\"} * 4 > 0)",
     "legendFormat": "                                                        {{project}} - {{ref}} - {{job_name}}"
    }
   ]
  },
  {
   "title": "Average Job Run Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - gitlab_ci_pipeline_job_timestamp{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"})"
    }
   ]
  },
  {
   "title": "Average Job Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_job_duration_seconds{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"})"
    }
   ]
  },
  {
   "title": "JOBS RUNS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_ci_pipeline_job_run_count{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}[1m])) by (project, ref, job_name) / sum(increase(gitlab_ci_pipeline_job_run_count{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}[1m])) by (project, ref, job_name)",
     "legendFormat": "{{ project }} - {{ ref }} - {{job_name}}"
    }
   ]
  },
  {
   "title": "SUCCESSFULLY COMPLETED",
   "type": "table",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "-max(time() - gitlab_ci_pipeline_job_timestamp{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) unless max(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_job_duration_seconds{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) unless (max(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) > 0)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_job_id{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, kind, job_name) unless (max(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, kind, job_name) > 0)"
    }
   ]
  },
  {
   "title": "RUNNING, FAILED OR NOT COMPLETED",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "-max(time() - gitlab_ci_pipeline_job_timestamp{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) unless max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_job_duration_seconds{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) unless (max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, job_name, kind) > 0)"
    },
    {
     "expr": "(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"running\"}) by (project, ref, job_name, kind) * 2) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"failed\"}) by (project, ref, job_name, kind) * 3) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"canceled\"}) by (project, ref, job_name, kind) * 4) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"created\"}) by (project, ref, job_name, kind) * 5) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"waiting_for_resource\"}) by (project, ref, job_name, kind) * 6) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"preparing\"}) by (project, ref, job_name, kind) * 7) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"pending\"}) by (project, ref, job_name, kind) * 8) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"skipped\"}) by (project, ref, job_name, kind) * 9) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"manual\"}) by (project, ref, job_name, kind) * 10) > 0 or\n(max(gitlab_ci_pipeline_job_status{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\", status=~\"scheduled\"}) by (project, ref, job_name, kind) * 11) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_job_id{project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, kind, job_name) unless (max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"$PROJECT\", ref=~\"$REF\", job_name=~\"$JOB\"}) by (project, ref, kind, job_name) > 0)"
    }
   ]
  }
 ]
}