gitlab:
  url: http://coding.codeages.work/
  # You can also configure the token using --gitlab-token
  # or the $GCPE_GITLAB_TOKEN environment variable
  token: zGEzm6VyGFSM4iysu2E1
projects:
  - name: edusoho/edusoho
    pull:
      environments:
        enabled: true
      pipeline:
        jobs:
          enabled: true
      refs:
        branches:
          enabled: true
          regexp: "^master|develop|release/.*|sprint/.*|project/.*$"
          max_age_seconds: 2592000
        tags:
          enabled: true
          regexp: ".*"
          max_age_seconds: 2592000
        merge_requests:
          enabled: true
          max_age_seconds: 259200
    
# wildcards:
#   - owner:
#       name: root
#       kind: user